<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(PDFsharpTargetFrameworks_Exe)</TargetFrameworks>
    <AssemblyName>ReadC2paInfo,PDFsharp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\foundation\src\PDFsharp\src\PdfSharp\PdfSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Cbor" />
  </ItemGroup>

</Project>
