// PDFsharp - A .NET library for processing PDF
// See the LICENSE file in the solution root for more information.

namespace PdfSharp
{
    /// <summary>
    /// Represents IDs for error and diagnostic messages generated by PDFsharp.
    /// </summary>
    // ReSharper disable once InconsistentNaming
    enum PSMsgID
    {
        // ----- General Messages ---------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        SampleMessage1,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        SampleMessage2,

        // ----- XGraphics Messages ---------------------------------------------------------------

        // ----- PDF Messages ----------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        NameMustStartWithSlash,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UserOrOwnerPasswordRequired,

        // ----- PdfParser Messages -------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UnexpectedToken,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UnknownEncryption,
    }
}