// MigraDoc - Creating Documents on the Fly
// See the LICENSE file in the solution root for more information.

namespace MigraDoc.DocumentObjectModel
{
    /// <summary>
    /// Represents IDs for error and diagnostic messages generated by the MigraDoc DOM.
    /// </summary>
    enum DomMsgID
    {
        // ----- General Messages ---------------------------------------------------------------------
        StyleExpected,
        BaseStyleRequired,
        EmptyBaseStyle,
        InvalidFieldFormat,
        InvalidInfoFieldName,
        UndefinedBaseStyle,
        InvalidUnitValue,
        InvalidUnitType,
        InvalidEnumValue,
        InvalidEnumForLeftPosition,
        InvalidEnumForTopPosition,
        InvalidColorString,
        InvalidFontSize,
        InsertNullNotAllowed,
        ParentAlreadySet,
        MissingObligatoryProperty,
        InvalidDocumentObjectType,

        // ----- DdlReader Messages -------------------------------------------------------------------

        Success = 1000,

        SymbolExpected,
        SymbolsExpected,
        OperatorExpected,
        KeyWordExpected,
        EndOfFileExpected,
        UnexpectedEndOfFile,

        StyleNameExpected,

        // --- old ---
        //    Internal,

        UnexpectedSymbol,

        IdentifierExpected,
        BoolExpected,
        RealExpected,
        IntegerExpected,
        //    IntegerOrIdentifierExpected,
        StringExpected,
        NullExpected,
        //    SymbolExpected,
        NumberExpected,

        InvalidEnum,
        //    InvalidFlag,
        //    InvalidStyle,
        //    InvalidStyleDefinition,
        InvalidType,
        InvalidAssignment,
        InvalidValueName,
        //    InvalidOperation,
        //    InvalidFormat,
        InvalidRange,
        InvalidColor,
        InvalidFieldType,
        InvalidValueForOperation,
        InvalidSymbolType,

        //    ValueOutOfRange,

        MissingBraceLeft,
        MissingBraceRight,
        MissingBracketLeft,
        MissingBracketRight,
        MissingParenLeft,
        MissingParenRight,
        //    MissingSemicolon,
        MissingComma,

        //    MissingDocumentPart,
        //    MissingEof,
        //    MissingIdentifier,
        //    MissingEndBuildingBlock,
        //    MissingSymbol,
        //    MissingParameter,

        SymbolNotAllowed,
        SymbolIsNotAnObject,
        //    BlockcommentOutsideCodeBlock,
        //    EOFReachedMissingSymbol,
        //    UnexpectedEOFReached,
        //    StyleAlreadyDefined,
        //    MultipleDefaultInSwitch,
        //    UnexpectedNewlineInDirective,
        //    UnexpectedSymbolInDirective,

        //    UnknownUnitOfMeasure,
        //    UnknownValueOperator,
        //    UnknownCodeSymbol,
        //    UnknownScriptSymbol,
        //    UnknownFieldSpecifier,
        //    UnknownFieldOption,
        //    UnknownValueType,
        //    UnknownEvaluationType,
        //    UnknownColorFunction,
        //    UnknownAxis,
        UnknownChartType,

        //    MisplacedCompilerSettings,
        //    MisplacedScopeType,
        //    TooMuchCells,
        NoAccess,

        //    FileNotFound,
        //    NotSupported,

        NewlineInString,
        EscapeSequenceNotAllowed,
        //    SymbolsNotAllowedInsideText,
        NullAssignmentNotSupported,
        OutOfRange,

        //    Warning_StyleOverwrittenMoreThanOnce,
        //    Warning_StyleAndBaseStyleAreEqual,
        //    Warning_NestedParagraphInParagraphToken,
        UseOfUndefinedBaseStyle,
        UseOfUndefinedStyle,

        //    NestedFootnote,
        //    ImageInFootnote,
        //    ShapeInFootnote
    }
}
